---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.16.0
  commands:
  - apk add -U curl git
  - git fetch origin
  - git reset --hard origin/$${BRANCH}
  - git checkout $${BRANCH}
  - bin/run.sh
  environment:
    ACTION: deploy
    BRANCH: master
    KUBE_TOKEN_ACP_NOTPROD:
      from_secret: kube_token_acp_notprod
    KUBE_TOKEN_ACP_PROD:
      from_secret: kube_token_acp_prod
    KUBE_TOKEN_ACP_TEST:
      from_secret: kube_token_acp_test
  when:
    event:
    - promote

...
