apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .DEPLOYMENT_NAME }}
spec:
  podSelector:
    matchLabels:
      name: {{ .DEPLOYMENT_NAME }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-internal
    - namespaceSelector:
        matchLabels:
          name: ingress-external
    ports:
    - protocol: TCP
      {{- if eq .ENABLE_KEYCLOAK "true" }}
      port: 10443
      {{- else }}
      port: 10444
      {{- end }}
