apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .DEPLOYMENT_NAME }}-service-tls
spec:
  secretName: {{ .DEPLOYMENT_NAME }}-service-tls-cmio
  issuerRef:
    name: platform-ca
    kind: ClusterIssuer
  commonName: flask-app.{{ .KUBE_NAMESPACE }}.svc.cluster.local
  dnsNames:
  - flask-app
  - flask-app.{{ .KUBE_NAMESPACE }}.svc