apiVersion: v1
kind: Service
metadata:
  name: {{ .DEPLOYMENT_NAME }}
  labels:
    name: {{ .DEPLOYMENT_NAME }}
    service: {{ .DEPLOYMENT_NAME }}
spec:
  ports:
    - name: https
      {{- if eq .ENABLE_KEYCLOAK "true" }}
      port: 10443
      {{- else }}
      port: 10444
      {{- end }}
  selector:
    name: {{ .DEPLOYMENT_NAME }}
